### ISSUE TITLE
lip_mpv_dataset as training dataset pre-processing

### ISSUE THREAD

**Issue by deeppppp** [rubelchowdhury20/Neural-Re-Rendering-of-Humans-from-a-Single-Image#2]
"The LIP dataset(Image-based Multi-pose Virtual Try On) was used to train the model."
This dataset comes as:
"lip_mpv_dataset" folder within:

"all_poseA_poseB_clothes.txt"   (rows with 4 columns: "SC321E00D/SC321E00D-O11@13=person_whole_front.jpg"	"SC321E00D/SC321E00D-O11@15=person_whole_back.jpg"	"SC321E00D/SC321E00D-O11@12.1=cloth_front.jpg"	"train")

"MPV_192_256" a folder with subfolders:
"0VB21E007"
"1FI21D003"
..
each subfolder has several images of a model wearing the clothing and an image of just the clothing article.

---------------
main.py
--data_directory parameter in main.py defaults to:
'/media/tensor/EXTDRIVE/projects/virtual-try-on/dataset/lip_mpv_dataset/'

---------------
train.py 
tries to load a pickle file that doesn't exist in the project:
data_path + "lip_pairs.pkl

---------------
dataloader.py tries to load:
images from several folders:
self.path + "lip_images/"
self.path + "lip_dense/"
self.path + "lip_textures/"
self.path + "lip_apparels/"

---------------
It's clear that you did some pre-processing on the lip_mpv_dataset, stored an index in the pickle file and the results in the mentioned folders (dataloader.py)

Can you provide the tools for this pre-processing?
or at minimum describe what the outputs should contain..
for example "lip_dense" would be the DensePose of the input image from "lip_images", but what is the "lip_textures" and "lip_apparels"?

**Comment by rubelchowdhury20** [comment]
Hi @deeppppp , as you have mentioned lip_dense is nothing but DensePose information.
lip_textures is the texture image of the person, acquired using the DensePose information.
lip_apparels is the product image, whose name is something like this "SC321E00D/SC321E00D-O11@12.1=cloth_front.jpg" from the dataset.
Hope that answers your question!

**Comment by deeppppp** [comment]
Thank you for the quick reply, and happy New Year.

"lip_textures is acquired from DensePose information" is still unclear.

DensePose textures are in Atlas form (24 parts), while you seem to work with the SMPL (Normal) texture form, looking at the Paper at http://gvv.mpi-inf.mpg.de/projects/NHRR/data/1415.pdf
 
Do you convert the Atlas textures to Normal form via a tool like UVTextureConverter?
---------
https://github.com/facebookresearch/DensePose/issues/68
https://github.com/kuboshizuma/UVTextureConverter/blob/master/notebook/convert_texture_between_normal_and_altas.ipynb

**Comment by deeppppp** [comment]
additional question on the textures, what dimensions are they?

I assume they are 256x256 with the dataset input images at 192x256
is that correct?

**Comment by deeppppp** [comment]
Thank you, and Happy New Year :)

**Comment by deeppppp** [comment]
Can you explain why lip_apparels is included in the dataset / training?

I don't see it being used in the architecture from the paper:
http://gvv.mpi-inf.mpg.de/projects/NHRR/data/1415.pdf
