### ISSUE TITLE
Something about your texture map

### ISSUE THREAD

**Issue by Ankh97** [rubelchowdhury20/Neural-Re-Rendering-of-Humans-from-a-Single-Image#6]
Hi, Rubel  Chowdhury! I'm interested in your prominent work . But I have some questions when reading your code. In the paper, the UV texture map Ts is as the normal texture of SMPL model,like this
![test3_256text](https://user-images.githubusercontent.com/65743414/112258240-1c753a00-8ca1-11eb-9ea7-9b5e20179948.png)
Howerver, in your code models/feature_render.py , you write
https://github.com/rubelchowdhury20/Neural-Re-Rendering-of-Humans-from-a-Single-Image/blob/5ccdf4535be00df6fb22f85bfa71df7ed70e8eb2/modules/models/feature_render.py#L29
which means your texture are the atlas texture?
So I wonder what kind of your texture map is? SMPL or atlas?

**Comment by rubelchowdhury20** [comment]
Hi Ankh, I have used the atlas texture map.
